name: quiver_log
version: 1.0.1
author: Adam Bender <bendera@google.com>
description: A logging utility for Dart, part of the quiver utilities
homepage: https://github.com/google/quiver-log
environment:
  sdk: '>=0.8.7'
documentation: http://google.github.io/quiver-log/
dependencies:
  intl: '>=0.9.9'
  logging: '>=0.9.0'
  path: '>=1.1.0'
  polymer: '>=0.8.10'
dev_dependencies:
  unittest: '>=0.10.0'
  mock: '>=0.10.0'