name: quiver_log
version: 1.0.7-dev.1
author: Adam Bender <bendera@google.com>
description: A logging utility for Dart, part of the quiver utilities
homepage: https://github.com/google/quiver-log
environment:
  sdk: '>=1.2.4 <3.0.0'
documentation: http://google.github.io/quiver-log/
dependencies:
  intl: '>=0.9.9 <0.20.0'
  logging: '>=0.9.0 <0.20.0'
dev_dependencies:
  test: '>=0.12.13'
